//usuario

insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Helge', 'Kupker', '22185 Carioca Park', 'hkupker0@pcworld.com', '4XmYtQwiJEv', 'https://robohash.org/omniscorruptiomnis.png?size=50x50&set=set1', '117-369-8783', 'PROPIETARIO');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Bernard', 'Humphries', '95 Lakewood Parkway', 'bhumphries1@marriott.com', 'SvObmtgQg', 'https://robohash.org/etundeaccusantium.png?size=50x50&set=set1', '117-369-8783', 'PROPIETARIO');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Hermy', 'Tenney', '902 West Terrace', 'htenney2@comsenz.com', 'wDBReucHQ', 'https://robohash.org/quiconsequaturlaudantium.png?size=50x50&set=set1', '117-369-8783', 'PROPIETARIO');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Herculie', 'Daniellot', '1 Jenna Center', 'hdaniellot3@ftc.gov', 'Dx1bNEM3UM6a', 'https://robohash.org/sitdelenitisequi.png?size=50x50&set=set1', '117-369-8783', 'PROPIETARIO');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Mahala', 'Pointon', '51 Northfield Circle', 'mpointon4@scientificamerican.com', 'aqWM4jbY', 'https://robohash.org/hicmollitiaet.png?size=50x50&set=set1', '117-369-8783', 'GESTOR');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Lanie', 'Looney', '355 Kings Crossing', 'llooney5@apache.org', 'NtpfXruuDqR', 'https://robohash.org/rationeeumodio.png?size=50x50&set=set1', '117-369-8783', 'GESTOR');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Ashleigh', 'Kiledal', '6212 Nobel Alley', 'akiledal6@ftc.gov', 'EKsncu1IWjf6', 'https://robohash.org/asperioresnonea.png?size=50x50&set=set1', '117-369-8783', 'GESTOR');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Zea', 'Carous', '6 Melvin Avenue', 'zcarous7@slideshare.net', 'TS5T6axeDel', 'https://robohash.org/quosateligendi.png?size=50x50&set=set1', '117-369-8783', 'GESTOR');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Fredric', 'Lancetter', '23 Chive Road', 'flancetter8@i2i.jp', 'CtzAV4uC', 'https://robohash.org/dignissimosautaut.png?size=50x50&set=set1', '117-369-8783', 'GESTOR');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Hillery', 'Burgott', '8578 Waywood Pass', 'hburgott9@dmoz.org', 'pKjSJU', 'https://robohash.org/laboriosamutnobis.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Horatia', 'Gerrietz', '77300 Rutledge Circle', 'hgerrietza@upenn.edu', 'nykrzTxQ', 'https://robohash.org/voluptatetemporaautem.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Fae', 'Jado', '5 Anthes Point', 'fjadob@google.com.br', '5yZwUkpZuCr', 'https://robohash.org/consequaturaliquidqui.png?size=50x50&set=set1','117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Humfrid', 'Codman', '70 Artisan Parkway', 'hcodmanc@sourceforge.net', '4KAdDBymprw', 'https://robohash.org/aperiamsuscipitnisi.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Anni', 'Vittery', '82323 Express Court', 'avitteryd@chicagotribune.com', '8BqAMnZ87WYz', 'https://robohash.org/veritatisetillo.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Orelia', 'Skey', '63 Village Green Trail', 'oskeye@zimbio.com', 'C5cBY8FF8bRs', 'https://robohash.org/harummolestiaeea.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Carlene', 'Salaman', '466 Prentice Hill', 'csalamanf@ted.com', '5QC4zuSy5LFO', 'https://robohash.org/enimaccusantiumsint.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Suzanna', 'Di Giacomo', '04178 Reindahl Junction', 'sdigiacomog@diigo.com', '7alTKI35', 'https://robohash.org/quidoloresiure.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Ailey', 'Elderton', '81 Bayside Crossing', 'aeldertonh@auda.org.au', '4b1NOndwO', 'https://robohash.org/rerumdolorenam.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Haskel', 'Gillmore', '5 Dovetail Circle', 'hgillmorei@columbia.edu', 'AyomlMd3vc4', 'https://robohash.org/cupiditateestvoluptate.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');
insert into users (id,nombre, apellidos, direccion, email, telefono, avatar, password, role) values (uuid(),'Fred', 'Jenicke', '45408 Schiller Alley', 'fjenickej@va.gov', 'YLfyEe', 'https://robohash.org/oditfacerenon.png?size=50x50&set=set1', '117-369-8783', 'ADMIN');



//vivienda

insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Home Ing', 'Buena zona de playa', 'https://robohash.org/pariaturametaut.png?size=50x50&set=set1', 40.7559095, '156 Granby Hill', '44071', 'constantina', 'Spain', 'vivienda antigua', 113707, 2, 138, 4, true, true, true);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Zaam-Dox', 'Buenas vistar', 'https://robohash.org/repellendusessequis.png?size=50x50&set=set1', 36.5292176, '86 Mcguire Crossing', '11005', 'tocina', 'Spain', 'alquiler', 74946, 3, 170, 4, false, true, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Flowdesk', 'En centro ciudad', 'https://robohash.org/quamdoloresexpedita.png?size=50x50&set=set1', 37.1952335, '879 Texas Way', '18015', 'lora del rio', 'Spain', 'vivienda antigua', 106917, 3, 100, 3, false, true, true);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Konklab', 'Buenas vistar', 'https://robohash.org/voluptatibussintoptio.png?size=50x50&set=set1', 38.8794495, '9827 Redwing Court', '06010', 'el pedroso', 'Spain', 'alquiler', 89099, 1, 149, 1, false, false, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Bigtax', 'Buenas vistar', 'https://robohash.org/illodoloremaut.png?size=50x50&set=set1', 42.2470995, '65913 Ryan Plaza', '17080', 'Villanueva del rio y minas', 'Spain', 'alquiler', 68033, 3, 72, 4, false, true, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Pannier', 'En centro ciudad', 'https://robohash.org/eumoditmodi.png?size=50x50&set=set1', 40.3954764, '450 Del Sol Court', '28045', 'lebrija', 'Spain', 'vivienda nueva', 65219, 2, 136, 4, false, false, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Span', 'Buenas vistar', 'https://robohash.org/eoscommodiquo.png?size=50x50&set=set1', 39.9863563, '334 Esker Way', '12100', 'constantina', 'Spain', 'vivienda antigua', 75050, 3, 89, 3, true, true, true);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Redhold', 'En centro ciudad', 'https://robohash.org/undepossimusdolores.png?size=50x50&set=set1', 43.5414515, '724 Hallows Street', '33404', 'villaverde', 'Spain', 'vivienda antigua', 98978, 1, 64, 1, false, false, true);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Treeflex', 'Buenas vistar', 'https://robohash.org/inciduntsaepenemo.png?size=50x50&set=set1', 42.4576548, '59 Vahlen Park', '26070', 'constantina', 'Spain', 'alquiler', 89322, 2, 143, 1, false, false, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Flowdesk', 'En centro ciudad', 'https://robohash.org/ipsumminuslaborum.png?size=50x50&set=set1', 42.214405, '48592 Arapahoe Drive', '36210', 'constantina', 'Spain', 'vivienda antigua', 117097, 4, 102, 4, false, false, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Zamit', 'En centro ciudad', 'https://robohash.org/quirerumasperiores.png?size=50x50&set=set1', 38.2911575, '29356 Evergreen Drive', '03203', 'Villanueva del rio y minas', 'Spain', 'alquiler', 92207, 2, 80, 2, true, false, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Fix San', 'Buenas vistar', 'https://robohash.org/fugitsequisunt.png?size=50x50&set=set1', 43.4880374, '506 Tennessee Court', '15490', 'constantina', 'Spain', 'alquiler', 108468, 1, 119, 1, true, false, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Zaam-Dox', 'Buenas vistar', 'https://robohash.org/blanditiismaximeomnis.png?size=50x50&set=set1', 36.5292176, '610 Coolidge Alley', '11005', 'cantillana', 'Spain', 'vivienda nueva', 87350, 3, 123, 3, true, false, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Vagram', 'Buenas vistar', 'https://robohash.org/accusantiumdebitisea.png?size=50x50&set=set1', 36.7203407, '653 Macpherson Pass', '29015', 'lora del rio', 'Spain', 'alquiler', 98015, 3, 169, 2, false, true, true);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Ronstring', 'Buena zona de playa', 'https://robohash.org/doloremfacerevoluptatibus.png?size=50x50&set=set1', 43.5162166, '77506 Summer Ridge Place', '33209', 'constantina', 'Spain', 'alquiler', 70051, 1, 132, 4, true, false, true);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Redhold', 'En centro ciudad', 'https://robohash.org/quisquamquiapariatur.png?size=50x50&set=set1', 36.5292176, '15 Namekagon Terrace', '11005', 'villaverde', 'Spain', 'alquiler', 90583, 3, 135, 4, true, true, true);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Bigtax', 'Buena zona de playa', 'https://robohash.org/eaqueetqui.png?size=50x50&set=set1', 37.3100775, '535 Hansons Park', '41703', 'el pedroso', 'Spain', 'vivienda nueva', 108657, 3, 106, 2, false, true, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Otcom', 'En centro ciudad', 'https://robohash.org/inciduntcorporisaut.png?size=50x50&set=set1', 40.500471, '68 Southridge Way', '28050', 'lora del rio', 'Spain', 'vivienda nueva', 69934, 3, 151, 3, true, true, true);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Y-Solowarm', 'Buena zona de playa', 'https://robohash.org/velitquisquameveniet.png?size=50x50&set=set1', 42.2390986, '034 Evergreen Trail', '36215', 'cantillana', 'Spain', 'vivienda antigua', 72097, 4, 155, 4, false, false, false);
insert into vivienda (titulo, descripcion, avatar, latlng, direccion, codigo_postal, poblacion, provincia, tipo, precio, num_habitaciones, metros_cuadrados, num_banyos, tiene_piscina, tiene_ascensor, tiene_garaje) values ('Aerified', 'Buena zona de playa', 'https://robohash.org/asperioresvoluptatemullam.png?size=50x50&set=set1', 43.3057431, '7795 Maywood Lane', '20010', 'constantina', 'Spain', 'vivienda nueva', 89542, 4, 134, 3, true, true, false);


//inmobiliaria

insert into inmobiliaria (nombre, email, telefono) values ('Irita', 'iborge0@skype.com', '769-657-3188');
insert into inmobiliaria (nombre, email, telefono) values ('Crystal', 'cmcilraith1@livejournal.com', '868-949-6197');
insert into inmobiliaria (nombre, email, telefono) values ('Prentice', 'plarmour2@opensource.org', '258-499-3727');
insert into inmobiliaria (nombre, email, telefono) values ('Nora', 'ntilbrook3@issuu.com', '763-110-8907');
insert into inmobiliaria (nombre, email, telefono) values ('Waly', 'wcanedo4@ed.gov', '760-326-7128');
insert into inmobiliaria (nombre, email, telefono) values ('Marijo', 'mtourle5@123-reg.co.uk', '632-591-0671');
insert into inmobiliaria (nombre, email, telefono) values ('Zorana', 'zstorks6@nps.gov', '117-369-8783');
insert into inmobiliaria (nombre, email, telefono) values ('Paxton', 'pfinnigan7@tamu.edu', '939-276-3201');
insert into inmobiliaria (nombre, email, telefono) values ('Dietrich', 'dleckey8@patch.com', '738-554-0067');
insert into inmobiliaria (nombre, email, telefono) values ('Dominick', 'dsanzio9@mozilla.org', '779-651-1489');
insert into inmobiliaria (nombre, email, telefono) values ('Marielle', 'mstuttera@example.com', '999-741-4981');
insert into inmobiliaria (nombre, email, telefono) values ('Karen', 'kaitkenb@icq.com', '621-877-5305');
insert into inmobiliaria (nombre, email, telefono) values ('Tibold', 'tmcqueenc@harvard.edu', '458-584-4646');
insert into inmobiliaria (nombre, email, telefono) values ('Miguel', 'mwinksd@nymag.com', '100-591-5539');
insert into inmobiliaria (nombre, email, telefono) values ('Emilie', 'emerigote@imgur.com', '187-126-2375');
insert into inmobiliaria (nombre, email, telefono) values ('Ced', 'cdunthornef@umich.edu', '712-625-0993');
insert into inmobiliaria (nombre, email, telefono) values ('Dede', 'ddedomenicog@freewebs.com', '270-358-6284');
insert into inmobiliaria (nombre, email, telefono) values ('Harmon', 'hvanyushinh@telegraph.co.uk', '208-539-8224');
insert into inmobiliaria (nombre, email, telefono) values ('Isidoro', 'ishinni@1688.com', '674-966-2475');
insert into inmobiliaria (nombre, email, telefono) values ('Darryl', 'dantuonij@ow.ly', '734-549-6600');
insert into inmobiliaria (nombre, email, telefono) values ('Marcela', 'mdymokek@reddit.com', '766-306-8406');
insert into inmobiliaria (nombre, email, telefono) values ('Jyoti', 'jdunsterl@ustream.tv', '582-552-6134');
insert into inmobiliaria (nombre, email, telefono) values ('Brandy', 'bbotgerm@psu.edu', '967-963-1100');
insert into inmobiliaria (nombre, email, telefono) values ('Sandy', 'ssmithern@scribd.com', '552-751-4671');
insert into inmobiliaria (nombre, email, telefono) values ('Shayne', 'sarbono@jugem.jp', '104-620-8408');
insert into inmobiliaria (nombre, email, telefono) values ('Anabal', 'akennermannp@army.mil', '485-157-1248');
insert into inmobiliaria (nombre, email, telefono) values ('Clayson', 'cjostq@51.la', '656-281-1839');
insert into inmobiliaria (nombre, email, telefono) values ('Maddie', 'mivimeyr@geocities.jp', '588-293-5479');
insert into inmobiliaria (nombre, email, telefono) values ('Ebony', 'ehoflers@ovh.net', '634-203-2810');
insert into inmobiliaria (nombre, email, telefono) values ('Sheena', 'sblinmant@opera.com', '948-415-3078');